### ISSUE TITLE
CODE RUB: Get Project In Good State

### ISSUE THREAD

**Issue by glhays** [pratikkaje/ExpenseTracker.Core#15]
Currently there is a build error, code should not be merged or committed if the local development environment is not in a good state. The Infrastructure Build project ensures a system in good state.
```
Error	CS8636	Invalid option 'disble' for /nullable; must be 'disable', 'enable', 'warnings' or ions'	ExpenseTracker.Core.Infrastructure.Build
```

**Comment by pratikkaje** [comment]
Resolve in /users/pratikkaje/infra-configure-Build branch
