### ISSUE TITLE
ACCEPTANCE: Models Transactions Add 

### ISSUE THREAD

**Issue by glhays** [pratikkaje/ExpenseTracker.Core#3]
Acceptance tests require there own models within the project, do not use project shared models.
If a model changes in the core model the acceptance test can help discover these changes. You can copy the class to a appropriate folder within the acceptance project.

**Comment by pratikkaje** [comment]
Noted. I will remove code related to Authorization for now.

**Comment by glhays** [comment]
@pratikkaje as in so.... Can not tell if you received my comment above based on your comment.
![image](https://github.com/pratikkaje/ExpenseTracker.Core/assets/42452283/73dba792-40ff-44f6-9e09-d4be86c6666a)

**Comment by pratikkaje** [comment]
I missed this. I will implement this today. Thanks for highlighting.
