### ISSUE TITLE
FOUNDATIONS: Users Add

### ISSUE THREAD

**Issue by glhays** [pratikkaje/ExpenseTracker.Core#6]
Adds the User foundation services
Can be closed if the services are only going to be managed via the Identity system

**Comment by pratikkaje** [comment]
User Foundation service is present. I will remove the RegisterUserAsync method from service later once I start implementing Authorization for the API.
![image](https://github.com/pratikkaje/ExpenseTracker.Core/assets/88729747/efd1c57e-5e1b-4fb9-864f-f6ec0f6267e4)
